### PR TITLE
Fix order attributes

### PR DESCRIPTION
**Pull request by bramstroker**
In Magento (CE) order entities are flat, they do not use the EAV structure. This fix will use the table schema to query the available attributes.

### CODE REVIEW

**Comment by Swahjak** [comment]
@bramstroker I'm not quite sure what is happening here, but seeing `SELECT column_name, column_comment FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = ?` makes my hair stand up. This is neither valid Magento 2 code, and I'm pretty sure any well granted database doesn't allow access to `information_schema`.

**Comment by bramstroker** [comment]
@Swahjak Do you experience issues with this in your installation? I'm not really sure about your concerns. Magento uses the information schema extensively for example for declaritive schema. When you don't grant access to information schema magento setup upgrade will not work. 
I think the reason @pmzandbergen queries the information schema directly without using the Magento schema classes is because he needs the comments from the database to present some meaningful labels to the end user. But maybe he can elaborate some more.

**Comment by Swahjak** [comment]
Magento doesn't use the information schema extensively, it is used almost exclusively in the `/Magento\Framework\Setup/` namespace (and not to make runtime queries). And even if the Core of a framework uses something doesn't mean it's free to use. Then there is the usage of database metadata to show 'labels' on the frontend (admin area frontend). Why not use the EAV model? Probably because it doesn't actually contain all the columns that are available, but that's just other extension (developers) misusing Magento. But then again when retrieving the values the code _does_ use the EAV model https://github.com/EmicoEcommerce/Magento2RobinHq/blob/731e7343750e89e757df1b547461a142bbb0f5b7/src/DataProvider/EavAttribute/AttributeRetriever.php#L35 and has a fallback to `null` resulting in no data if there is no EAV.

I'm sorry if I overreacted. But using _raw queries_ (which is against https://github.com/magento/magento-coding-standard) to fetch _'some comments'_ from a database table using the _information schema_, used to _display for end users_ (admins) while perfectly valid alternatives are available (and even if they are not, that would be a Magento limitation) rubs me the wrong way.

That being said; now that I've looked through the code base I must say it's pretty neat :ok_hand:. Though we have some performance issues on the API backends being a bit heavy for the purposes RobinHQ uses them for (realtime searches using `like` queries on operational heavy tables such as `sales_order` that are blocking to users using RobinHQ). Might propose a solution to that in another issues / pull after digging into it a bit more.

**Comment by wouter-toppy** [comment]
@pmzandbergen  This is still a issue for us. in your last commit you said you replaced the raw query on the information scheme, but you didnt. you only changed it from direct text to a query builder. but the effect it still the same, a raw query on the information scheme. which doesnt work for us. please fix the issue where we dont have to use the information scheme. as @Swahjak  suggested.

**Pull request merged**
